site_name: AEMET Weather Intelligence
site_description: Proyecto de ingeniería, análisis y predicción meteorológica
site_author: Javier Miñarro

theme:
  name: material
  language: es

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md
  - Fuente de datos: data-source.md
  - Diario de desarrollo: development-log.md